<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check offer</name>
   <tag></tag>
   <elementGuidId>b877be06-c0c7-41b4-bf3a-443bc861f0e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='officeHome__content']/ohp-hero/div/div/div/ohp-app-tiles-list/div/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Start newCreate a document online. Use the arrow keys to navigate and enter to select Outlook  OneDrive  Word  Excel  PowerPoint  OneNote  SharePoint  Teams  Sway All apps' or . = 'Start newCreate a document online. Use the arrow keys to navigate and enter to select Outlook  OneDrive  Word  Excel  PowerPoint  OneNote  SharePoint  Teams  Sway All apps')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fluent-tiles</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start newCreate a document online. Use the arrow keys to navigate and enter to select Outlook  OneDrive  Word  Excel  PowerPoint  OneNote  SharePoint  Teams  Sway All apps</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;officeHome__content&quot;)/ohp-hero[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;hero-section hero-section--padded hero-section__homepage--padded&quot;]/div[@class=&quot;width-restrictor width-restrictor--responsive&quot;]/div[@class=&quot;hero-container&quot;]/ohp-app-tiles-list[@class=&quot;ng-tns-c0-0 ng-star-inserted&quot;]/div[@class=&quot;app-tiles-list-component ng-trigger ng-trigger-fadeOut&quot;]/div[@class=&quot;tiles-section__container&quot;]/div[@class=&quot;ng-tns-c0-0&quot;]/div[@class=&quot;fluent-tiles&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='officeHome__content']/ohp-hero/div/div/div/ohp-app-tiles-list/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Install Office'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Good afternoon, KATHAWUT'])[1]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ohp-app-tiles-list/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='officeHome__content']/ohp-hero/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Microsoft Office Home'])[2]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ohp-hero/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
