<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>head7</name>
   <tag></tag>
   <elementGuidId>439eb77e-fd6e-48eb-805a-e8078c8231c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='id-to-scroll']/div/div[2]/div/div[3]/div/p/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linenews2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>คณะสหเวชศาสตร์ มหาวิทยาลัยพะเยา จัด การอบรมฟื้นฟูวิชาการเทคนิคการแพทย์ประจำปี ม.พะเยา ครั้งที่ 2 (School of Allied Health Sciences (AHS), University of Phayao (UP) Presents 2nd UPMT Annual Update in Medical Technology)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>NewsRead.aspx?itemID=20120</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> คณะสหเวชศาสตร์ มหาวิทยาลัยพะเยา จัด การอบรมฟื้นฟูวิชาการเทคนิคการแพทย์ประจำปี ม.พะเยา ครั้งที่ 2 (School of Allied Health Sciences (AHS), University of Phayao (UP) Presents 2nd UPMT Annual Update in Medical Technology)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-to-scroll&quot;)/div[@class=&quot;row no-margin&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-sm-3&quot;]/div[@class=&quot;colored-box blockquote&quot;]/p[@class=&quot;linenews&quot;]/a[@class=&quot;linenews2&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-to-scroll']/div/div[2]/div/div[3]/div/p/a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'คณะสหเวชศาสตร์ มหาวิทยาลัยพะเยา จัด การอบรมฟื้นฟูวิชาการเทคนิคการแพทย์ประจำปี ม.พะเยา ครั้งที่ 2 (School of Allied Health Sciences (AHS), University of Phayao (UP) Presents 2nd UPMT Annual Update in Medical Technology)')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':: มหาวิทยาลัยพะเยา'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':: ห้องภูกามยาว 1 (PKY1) อาคารเรียนรวมหลังเก่า มหาวิทยาลัยพะเยา'])[1]/following::a[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':: โรงแรม เซ็นทารา ดวงตะวัน เชียงใหม่ (Centara Duang Tawan Chiang Mai Hotel)'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':: อาคารเทคโนโลยีสารเสนเทศและการสื่อสาร'])[1]/preceding::a[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='คณะสหเวชศาสตร์ มหาวิทยาลัยพะเยา จัด การอบรมฟื้นฟูวิชาการเทคนิคการแพทย์ประจำปี ม.พะเยา ครั้งที่ 2 (School of Allied Health Sciences (AHS), University of Phayao (UP) Presents 2nd UPMT Annual Update in Medical Technology)']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'NewsRead.aspx?itemID=20120')])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/p/a[2]</value>
   </webElementXpaths>
</WebElementEntity>
